class GameSettings:
    "Game constants"

    SNAKE_WIDTH = 64
    SNAKE_HEIGHT = 64

    BAIT_WIDTH = 64
    BAIT_HEIGHT = 64
    SNAKE_SPEED = 64

    SNAKE_GAME_SPEED = 100

    WIDTH = SNAKE_WIDTH * 20
    HEIGHT = SNAKE_HEIGHT * 15

    MENU_RECT_WIDTH = WIDTH // 5
    MENU_RECT_HEIGHT = HEIGHT // 18

    FAME_ONE = (WIDTH ) // 5 + MENU_RECT_WIDTH
    FAME_TWO = 1
    MENU_SINGLE_PLAYER_BUTTON_X_POS = MENU_RECT_WIDTH
    MENU_SINGLE_PLAYER_BUTTON_Y_POS = 0

    HALL_OF_FAME_FIRST_POS_X = MENU_RECT_WIDTH * 2 + 5
    HALL_OF_FAME_FIRTS_POS_Y = MENU_RECT_HEIGHT * 3
    
    HALL_OF_FAME_SECOND_POS_X = MENU_RECT_WIDTH * 2 + 5
    HALL_OF_FAME_SECOND_POS_Y = MENU_RECT_HEIGHT * 5
    
    HALL_OF_FAME_THIRD_POS_X = MENU_RECT_WIDTH * 2 + 5
    HALL_OF_FAME_THIRD_POS_Y = MENU_RECT_HEIGHT * 7

    HALL_OF_FAME_FORTH_POS_X = MENU_RECT_WIDTH * 2 + 5
    HALL_OF_FAME_FORTH_POS_Y = MENU_RECT_HEIGHT * 9

    HALL_OF_FAME_FIFTH_POS_X = MENU_RECT_WIDTH * 2 + 5
    HALL_OF_FAME_FIFTH_POS_Y = MENU_RECT_HEIGHT * 11

    MENU_MULIT_PLAYER_BUTTON_X_POS = MENU_RECT_WIDTH * 2 + 5
    MENU_MULIT_PLAYER_BUTTON_Y_POS = 0

    MULTI_PLAYER_SCORE_BOX = WIDTH - 120

    MULTI_PLAYER_PLAYER_TWO_WIN = (WIDTH //2, HEIGHT//2)

    MENU_SETTINGS_BUTTON_X_POS = MENU_RECT_WIDTH * 3 + 10
    MENU_SETTINGS_BUTTON_Y_POS = 0

    MENU_EXIT_GAME_BUTTON_X_POS = MENU_MULIT_PLAYER_BUTTON_X_POS
    MENU_EXIT_GAME_BUTTON_Y_POS = HEIGHT - MENU_RECT_HEIGHT

    RIGHT_CLICK = (True, False, False)